name: Debug Build Process

on:
  workflow_dispatch:  # Manual trigger

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and update package-lock.json
        run: npm install
        
      - name: List files in directory
        run: ls -la
        
      - name: Check Node.js and npm versions
        run: |
          node -v
          npm -v
          
      - name: Check package.json
        run: cat package.json
          
      - name: Check for required files
        run: |
          echo "Checking for required files..."
          [ -f "vite.config.ts" ] && echo "vite.config.ts exists" || echo "vite.config.ts MISSING"
          [ -f "tsconfig.json" ] || [ -f "jsconfig.json" ] && echo "tsconfig/jsconfig exists" || echo "tsconfig/jsconfig MISSING"
          [ -d "src" ] && echo "src directory exists" || echo "src directory MISSING"
          
      - name: Build project
        run: npm run build
        
      - name: Check build output
        if: always()
        run: |
          [ -d "dist" ] && echo "dist directory was created" && ls -la dist || echo "dist directory NOT created" 