name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Use Node.js to build locally first as a verification step
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and update package-lock.json
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: List build output
        run: ls -la dist
      
      # Now proceed with Docker build and deployment if local build succeeded
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: mamba-frontend:latest

      - name: Save Docker image
        run: |
          docker save mamba-frontend:latest > /tmp/mamba-frontend.tar
          ls -la /tmp/mamba-frontend.tar

      # Deploy to DigitalOcean
      - name: Upload configuration files to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "docker-compose.yml,nginx.conf"
          target: "/root/mamba-frontend"
          strip_components: 0

      - name: Upload Docker image to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "/tmp/mamba-frontend.tar"
          target: "/tmp"
          strip_components: 0
          timeout: 300s
          overwrite: true

      - name: Generate deployment ID
        id: deploy_id
        run: echo "DEPLOY_ID=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Deploy on droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: DEPLOY_ID=${{ steps.deploy_id.outputs.DEPLOY_ID }}
          script: |
            # Ensure directories exist
            mkdir -p /root/mamba-frontend
            
            # Verify the image file exists
            ls -la /tmp/mamba-frontend.tar
            
            # Load the Docker image
            docker load < /tmp/mamba-frontend.tar
            
            # Stop and remove existing container if exists
            if docker ps -a | grep -q mamba-frontend; then
              echo "Removing existing container"
              docker stop $(docker ps -a -q --filter="name=mamba-frontend") || true
              docker rm $(docker ps -a -q --filter="name=mamba-frontend") || true
            fi
            
            # Deploy using docker-compose with unique deployment ID
            cd /root/mamba-frontend
            export DEPLOY_ID="${DEPLOY_ID}"
            docker-compose down --remove-orphans || true
            docker-compose up -d
            
            # Verify deployment
            docker ps | grep mamba-frontend
            
            # Clean up
            rm -f /tmp/mamba-frontend.tar 